organisation: WirMachenWien
url: https://wirmachen.wien/blog/von-berlin-und-ljubljana-lernen-drei-neue-workshops/
email: info@wirmachen.wien
name: Toolbox für City Changer
description: Ein Handbuch von Wir machen Wien, Changing Cities und Prostorož aus
  dem Erasmus+-Projekt Toolbox für City Changer.
logo: logo.svg
image: cover.jpg
credit: Ein Handbuch von <a href="https://wirmachen.wien">WirMachenWien</a> im
  Rahmen der Toolbox für City Changer.
language: de
app-id: wien.wirmachen.toolbox
version: 1.0.0
