title: Zbirka orodij za spreminjanje mest
subtitle: Priročnik organizacij WirMachenWien, Changing Cities in Prostorož
creator: WirMachenWien
contributor: Changing Cities; Prostorož
description: Praktični priročnik za pobude, ki želijo svoje mesto narediti varnejše,
  bolj zeleno, vključujoče in odpornejše na podnebne spremembe ter za to potrebujejo
  orodja.
image: cover.jpg
publisher: WirMachenWien
publisher-url: https://wirmachen.wien
rightsholder: WirMachenWien in navedeni sodelujoči
rights: Zbrano iz javno dostopnih gradiv WirMachenWien in povezanih partnerskih organizacij.
  Pravice do predavanj, fotografij, dokumentov PDF in videoposnetkov ostajajo pri
  navedenih imetnikih pravic.
language: sl
date: 2026-09-03
modified: 2026-09-03
type: Priročnik
subject: Urbani razvoj; aktivizem; umirjanje prometa; sodelovanje
identifier: wmw-toolbox-city-changer-2026-sl
coverage: Dunaj, Berlin, Ljubljana; 2026
keywords: WirMachenWien, Erasmus+, superblok, Supergrätzl, Kiezblock, taktični urbanizem,
  oblikovanje ulic, mobilizacija, spremljanje, Dunaj
products:
  print-pdf:
    format: Tisk
    files:
    - 0-0-cover
    - 0-1-titlepage
    - 0-2-copyright
    - 0-3-contents
    - '01'
    - '02'
    - '03'
    - '04'
    - '05'
    - '06'
    toc: &id001
    - label: Naslovnica
      file: 0-0-cover
      class: frontmatter-entry
    - label: Naslovna stran
      file: 0-1-titlepage
      class: frontmatter-entry
    - label: Avtorske pravice
      file: 0-2-copyright
      class: frontmatter-entry
    - label: Vsebina
      file: 0-3-contents
      class: frontmatter-entry
    - label: 1. Zakaj ta zbirka orodij?
      file: '01'
    - label: 2. Kako začeti s superbloki
      file: '02'
    - label: 3. Taktični urbanizem in oblikovanje ulic
      file: '03'
    - label: 4. Mobilizacija in strategije sprememb
      file: '04'
    - label: '5. Spremljanje: pokažimo učinek'
      file: '05'
    - label: 6. Delovni načrt in viri
      file: '06'
  web:
    format: Na spletu
    files:
    - 0-0-cover
    - 0-1-titlepage
    - 0-2-copyright
    - 0-3-contents
    - '01'
    - '02'
    - '03'
    - '04'
    - '05'
    - '06'
    nav: *id001
  epub:
    format: E-knjiga
    files:
    - 0-0-cover: cover
    - 0-1-titlepage: title-page
    - 0-2-copyright: copyright-page
    - 0-3-contents: toc
    - '01'
    - '02'
    - '03'
    - '04'
    - '05'
    - '06'
    contents-page: 0-3-contents
    accessibility:
      summary: Ta publikacija je skladna s standardom WCAG 2.0 na ravni AA.
      access-mode: textual, visual
      access-mode-sufficient: textual
      accessibility-features: tableOfContents
      accessibility-hazards: unknown
  screen-pdf:
    format: PDF
    files:
    - 0-0-cover
    - 0-1-titlepage
    - 0-2-copyright
    - 0-3-contents
    - '01'
    - '02'
    - '03'
    - '04'
    - '05'
    - '06'
  app:
    format: Aplikacija
