import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';
import { languages } from '../handbook.config.ts';

const lang = z.enum(languages);

const book = defineCollection({
  loader: glob({ pattern: '**/*.mdx', base: './src/content/book' }),
  schema: z.object({
    title: z.string(),
    lang,
    // Render variant for the book page. Cover/title sheets are print-only
    // (generated by the download builders from works.json) and have no MDX
    // source file, so only web variants are valid here.
    // (Named "template": Astro reserves frontmatter `layout` for MDX layouts.)
    template: z
      .enum(['chapter', 'about', 'contents'])
      .default('chapter'),
    description: z.string().optional(),
  }),
});

const pages = defineCollection({
  loader: glob({ pattern: '**/*.mdx', base: './src/content/pages' }),
  schema: z.object({
    title: z.string(),
    lang,
    template: z.enum(['home', 'page', 'search']).default('page'),
    description: z.string().optional(),
    openerImage: z.string().optional(),
    openerImageAlt: z.string().optional(),
  }),
});

export const collections = { book, pages };
