import { defineCollection } from 'astro:content';
import { z } from 'astro/zod';
import { glob } from 'astro/loaders';
import { languages } from '../handbook.config.ts';

const lang = z.enum(languages);

const book = defineCollection({
  loader: glob({ pattern: '**/*.mdx', base: './src/content/book' }),
  schema: z.object({
    title: z.string(),
    lang,
    // Render variant for the book page. Cover/title/contents sheets are
    // print-only or virtual (generated by the download builders from
    // works.json) and have no MDX source file, so only web variants are
    // valid here. Chapters are full articles; sections are generic
    // front-matter pages (e.g. about) whose heading lives in the MDX body.
    // (Named "template": Astro reserves frontmatter `layout` for MDX layouts.)
    template: z
      .enum(['chapter', 'section'])
      .default('chapter'),
    description: z.string().optional(),
  }),
});

const pages = defineCollection({
  loader: glob({ pattern: '**/*.mdx', base: './src/content/pages' }),
  schema: z.object({
    title: z.string(),
    lang,
    template: z.enum(['home', 'page', 'search']).default('page'),
    description: z.string().optional(),
    openerImage: z.string().optional(),
    openerImageAlt: z.string().optional(),
  }),
});

// Preview pages (component showcase): MDX source rendered through the shared
// MdxContent scope, so demos use exactly the author-facing component set.
// The showcase is English-only by design (no language switcher in the CMS),
// so `lang` falls back to the default language.
const preview = defineCollection({
  loader: glob({ pattern: '**/*.mdx', base: './src/content/preview' }),
  schema: z.object({
    title: z.string(),
    lang: lang.default('en'),
  }),
});

export const collections = { book, pages, preview };
